# Generated by Django 2.0.6 on 2019-03-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190308_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='votes_total1',
            field=models.IntegerField(default=1),
        ),
    ]
